import type { Catalog } from "@/lib/types";

export const sampleCatalog: Catalog = {
  profiles: [],
  curriculums: [
    { id: "cambridge", name: "Cambridge", slug: "cambridge", display_order: 1, created_at: "2026-01-01T00:00:00.000Z" },
  ],
  levels: [
    { id: "igcse", curriculum_id: "cambridge", name: "IGCSE", slug: "igcse", display_order: 1, created_at: "2026-01-01T00:00:00.000Z" },
  ],
  subjects: [
    { id: "physics-0625", level_id: "igcse", name: "Physics", slug: "physics-0625", code: "0625", display_order: 1, created_at: "2026-01-01T00:00:00.000Z" },
  ],
  units: [
    { id: "unit-1", subject_id: "physics-0625", name: "Unit 1", slug: "unit-1", description: "Physical quantities and measurement foundations.", display_order: 1, created_at: "2026-01-01T00:00:00.000Z" },
  ],
  topics: [
    { id: "physical-quantities", unit_id: "unit-1", name: "Physical Quantities", slug: "physical-quantities", description: "Core quantities, units, and measurement language.", display_order: 1, created_at: "2026-01-01T00:00:00.000Z" },
  ],
  subTopics: [
    { id: "scalars-and-vectors", topic_id: "physical-quantities", name: "Scalars and Vectors", slug: "scalars-and-vectors", description: "Practice distinguishing magnitude-only quantities from directional quantities.", display_order: 1, created_at: "2026-01-01T00:00:00.000Z" },
  ],
  teachers: [
    {
      id: "teacher-amara",
      name: "Amara Perera",
      slug: "amara-perera",
      email: "amara@example.com",
      photo_url: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
      cover_url: "https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=1600&q=80",
      subjects: ["Physics 0625"],
      curriculums: ["Cambridge IGCSE"],
      qualifications: "BSc Physics, PGCE",
      experience_years: 8,
      short_bio: "Builds clear topical question pathways for Cambridge Physics learners.",
      biography: "Amara specializes in helping students turn syllabus points into repeatable problem-solving habits through topical MCQs and focused discussion videos.",
      social_links: { youtube: "https://youtube.com", linkedin: "https://linkedin.com" },
      created_at: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "teacher-naveen",
      name: "Naveen Silva",
      slug: "naveen-silva",
      email: "naveen@example.com",
      photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
      cover_url: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=80",
      subjects: ["Mathematics", "Additional Mathematics"],
      curriculums: ["Cambridge", "Edexcel"],
      qualifications: "MSc Mathematics Education",
      experience_years: 11,
      short_bio: "Creates compact explanations for high-frequency exam question types.",
      biography: "Naveen designs structured topic ladders that help students master concepts before moving to timed exam practice.",
      social_links: { youtube: "https://youtube.com" },
      created_at: "2026-01-01T00:00:00.000Z",
    },
  ],
  teacherSubjects: [{ id: "assignment-1", teacher_id: "teacher-amara", subject_id: "physics-0625", created_at: "2026-01-01T00:00:00.000Z" }],
  questionTypes: [
    {
      id: "qt-scalars-vectors-mcq",
      sub_topic_id: "scalars-and-vectors",
      teacher_id: "teacher-amara",
      type: "mcq",
      title: "Scalars and Vectors MCQ",
      description: "A short diagnostic MCQ set for the first pass through the topic.",
      display_order: 1,
      created_at: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "qt-scalars-vectors-structured",
      sub_topic_id: "scalars-and-vectors",
      teacher_id: "teacher-amara",
      type: "structured",
      title: "Scalars and Vectors Structured",
      description: "Written practice with marking scheme support.",
      display_order: 2,
      created_at: "2026-01-01T00:00:00.000Z",
    },
  ],
  questions: [
    {
      id: "q1",
      question_type_id: "qt-scalars-vectors-mcq",
      question_image_url: "https://dummyimage.com/960x540/ffffff/111827.png&text=Which+quantity+is+a+vector%3F+A+Mass+B+Speed+C+Velocity+D+Time",
      correct_answer: "C",
      marking_scheme: "",
      explanation: "Velocity includes both magnitude and direction.",
      difficulty: "easy",
      display_order: 1,
      created_at: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "q2",
      question_type_id: "qt-scalars-vectors-mcq",
      question_image_url: "https://dummyimage.com/960x540/ffffff/111827.png&text=Which+pair+contains+only+scalars%3F+A+Mass+and+time+B+Force+and+velocity+C+Weight+and+displacement+D+Acceleration+and+force",
      correct_answer: "A",
      marking_scheme: "",
      explanation: "Mass and time have magnitude only.",
      difficulty: "medium",
      display_order: 2,
      created_at: "2026-01-01T00:00:00.000Z",
    },
    {
      id: "q3",
      question_type_id: "qt-scalars-vectors-structured",
      question_image_url: "https://dummyimage.com/960x540/ffffff/111827.png&text=Explain+the+difference+between+distance+and+displacement.",
      correct_answer: null,
      marking_scheme: "1 mark for scalar/vector distinction. 1 mark for direction. 1 mark for clear example.",
      explanation: "Distance is scalar; displacement is vector.",
      difficulty: "medium",
      display_order: 1,
      created_at: "2026-01-01T00:00:00.000Z",
    },
  ],
  discussionVideos: [
    {
      id: "video-scalars-vectors",
      question_type_id: "qt-scalars-vectors-mcq",
      teacher_id: "teacher-amara",
      title: "Scalars and Vectors Discussion",
      youtube_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      youtube_video_id: "dQw4w9WgXcQ",
      description: "Walk through the key definitions, traps, and answer patterns for this MCQ set.",
      resources: "Download the syllabus checklist from your class folder.",
      created_at: "2026-01-01T00:00:00.000Z",
    },
  ],
};
