"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, CreditCard, Loader2, Save, Upload } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Settings = { id: string; payment_method: string; qr_image_url: string | null; account_name: string | null; instructions: string | null; is_active: boolean; subject_price: number | null; premium_price: number | null; currency: string };

export default function PaymentSettingsPage() {
  const supabase = useMemo(() => createClient(), []); const [settings, setSettings] = useState<Settings | null>(null); const [paymentMethod, setPaymentMethod] = useState("LankaQR"); const [accountName, setAccountName] = useState(""); const [instructions, setInstructions] = useState(""); const [subjectPrice, setSubjectPrice] = useState(""); const [premiumPrice, setPremiumPrice] = useState(""); const [currency, setCurrency] = useState("LKR"); const [isActive, setIsActive] = useState(true); const [qrUrl, setQrUrl] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { let mounted = true; async function load() { const { data, error: loadError } = await supabase.from("payment_settings").select("*").limit(1).maybeSingle(); if (!mounted) return; if (loadError) setError(loadError.message); else if (data) { const s = data as Settings; setSettings(s); setPaymentMethod(s.payment_method || "LankaQR"); setAccountName(s.account_name || ""); setInstructions(s.instructions || ""); setSubjectPrice(s.subject_price?.toString() || ""); setPremiumPrice(s.premium_price?.toString() || ""); setCurrency(s.currency || "LKR"); setIsActive(s.is_active); setQrUrl(s.qr_image_url || ""); } setLoading(false); } void load(); return () => { mounted = false; }; }, [supabase]);
  async function uploadQr(file: File) { setError(""); setMessage(""); if (!file.type.startsWith("image/")) { setError("Please select an image file."); return; } if (file.size > 5 * 1024 * 1024) { setError("QR image must be 5 MB or smaller."); return; } setUploading(true); const form = new FormData(); form.append("file", file); try { const response = await fetch("/api/admin/payment-qr", { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "QR upload failed."); setQrUrl(result.url); setMessage("QR image uploaded. Save settings to apply it."); } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : "QR upload failed."); } finally { setUploading(false); } }
  async function save() { setSaving(true); setError(""); setMessage(""); const payload = { payment_method: paymentMethod.trim() || "LankaQR", qr_image_url: qrUrl || null, account_name: accountName.trim() || null, instructions: instructions.trim() || null, is_active: isActive, subject_price: subjectPrice === "" ? null : Number(subjectPrice), premium_price: premiumPrice === "" ? null : Number(premiumPrice), currency: currency.trim().toUpperCase() || "LKR" }; if (payload.subject_price !== null && (!Number.isFinite(payload.subject_price) || payload.subject_price < 0)) { setError("Enter a valid subject price."); setSaving(false); return; } if (payload.premium_price !== null && (!Number.isFinite(payload.premium_price) || payload.premium_price < 0)) { setError("Enter a valid premium price."); setSaving(false); return; } const result = settings?.id ? await supabase.from("payment_settings").update(payload).eq("id", settings.id).select("*").single() : await supabase.from("payment_settings").insert(payload).select("*").single(); if (result.error) setError(result.error.message); else { setSettings(result.data as Settings); setMessage("Payment settings saved successfully."); } setSaving(false); }
  if (loading) return <div className="flex min-h-[400px] items-center justify-center text-sm text-muted-foreground"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading payment settings...</div>;
  return <div className="mx-auto max-w-4xl space-y-7"><div><p className="text-sm font-semibold text-primary">Administration</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight">Payment Settings</h1><p className="mt-2 text-sm text-muted-foreground">Control how students see and pay for subscriptions.</p></div>{error && <div className="rounded-xl border border-destructive/20 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}{message && <div className="flex items-center gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/5 px-4 py-3 text-sm text-emerald-700"><CheckCircle2 className="h-4 w-4" />{message}</div>}
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><CreditCard className="h-5 w-5" /></div><div><h2 className="font-bold">Payment method</h2><p className="mt-1 text-xs text-muted-foreground">These details are shown to students during checkout.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><label className="space-y-2 text-sm font-semibold">Payment method<input value={paymentMethod} onChange={(e) => setPaymentMethod(e.target.value)} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm font-normal outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" /></label><label className="space-y-2 text-sm font-semibold">Account name<input value={accountName} onChange={(e) => setAccountName(e.target.value)} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm font-normal outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" placeholder="e.g. iSkole Online" /></label></div><label className="mt-5 flex cursor-pointer items-center gap-3 rounded-xl border border-border bg-muted/30 p-4"><input type="checkbox" checked={isActive} onChange={(e) => setIsActive(e.target.checked)} className="h-4 w-4 accent-primary" /><span><span className="block text-sm font-bold">Accept payments</span><span className="block text-xs text-muted-foreground">When disabled, students should not be offered paid plans.</span></span></label></section>
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><h2 className="font-bold">Subscription pricing</h2><div className="mt-5 grid gap-5 sm:grid-cols-3"><label className="space-y-2 text-sm font-semibold">Subject price<input type="number" min="0" step="0.01" value={subjectPrice} onChange={(e) => setSubjectPrice(e.target.value)} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm font-normal outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" /></label><label className="space-y-2 text-sm font-semibold">Premium price<input type="number" min="0" step="0.01" value={premiumPrice} onChange={(e) => setPremiumPrice(e.target.value)} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm font-normal outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" /></label><label className="space-y-2 text-sm font-semibold">Currency<input value={currency} maxLength={3} onChange={(e) => setCurrency(e.target.value)} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm font-normal uppercase outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" /></label></div></section>
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><h2 className="font-bold">QR payment</h2><p className="mt-1 text-xs text-muted-foreground">Upload the QR image students should scan to make payment.</p><div className="mt-5 flex flex-col gap-5 sm:flex-row sm:items-start"><div className="flex h-48 w-48 shrink-0 items-center justify-center overflow-hidden rounded-2xl border border-dashed border-border bg-muted/30">{qrUrl ? <img src={qrUrl} alt="Payment QR" className="h-full w-full object-contain" /> : <span className="px-5 text-center text-xs text-muted-foreground">No QR image uploaded</span>}</div><div className="space-y-3"><label className="inline-flex h-10 cursor-pointer items-center gap-2 rounded-xl border border-border bg-card px-4 text-sm font-bold hover:bg-muted"><Upload className="h-4 w-4" />{uploading ? "Uploading..." : "Upload QR image"}<input type="file" accept="image/*" className="hidden" disabled={uploading} onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadQr(file); e.currentTarget.value = ""; }} /></label><p className="text-xs text-muted-foreground">PNG, JPG, WEBP or GIF · maximum 5 MB.</p></div></div></section>
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><h2 className="font-bold">Payment instructions</h2><textarea value={instructions} onChange={(e) => setInstructions(e.target.value)} rows={6} className="mt-4 w-full resize-y rounded-xl border border-input bg-background p-3 text-sm outline-none focus:border-primary focus:ring-4 focus:ring-primary/10" placeholder="Tell students how to make the payment and what reference to include..." /></section><div className="sticky bottom-4 flex justify-end"><button type="button" disabled={saving || uploading} onClick={() => void save()} className="flex h-11 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground shadow-sm transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"><Save className="h-4 w-4" />{saving ? "Saving..." : "Save payment settings"}</button></div></div>;
}
