"use client";

import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, CreditCard, Info, Loader2, Save, ShieldCheck, Upload } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Settings = { id: string; payment_method: string; qr_image_url: string | null; account_name: string | null; instructions: string | null; is_active: boolean; subject_price: number | null; premium_price: number | null; currency: string };

export default function PaymentSettingsPage() {
  const supabase = useMemo(() => createClient(), []);
  const [settings, setSettings] = useState<Settings | null>(null); const [paymentMethod, setPaymentMethod] = useState("LankaQR"); const [accountName, setAccountName] = useState(""); const [instructions, setInstructions] = useState(""); const [subjectPrice, setSubjectPrice] = useState(""); const [premiumPrice, setPremiumPrice] = useState(""); const [currency, setCurrency] = useState("LKR"); const [isActive, setIsActive] = useState(true); const [qrUrl, setQrUrl] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");

  useEffect(() => { let mounted = true; async function load() { const { data, error: loadError } = await supabase.from("payment_settings").select("*").limit(1).maybeSingle(); if (!mounted) return; if (loadError) setError(loadError.message); else if (data) { const s = data as Settings; setSettings(s); setPaymentMethod(s.payment_method || "LankaQR"); setAccountName(s.account_name || ""); setInstructions(s.instructions || ""); setSubjectPrice(s.subject_price?.toString() || ""); setPremiumPrice(s.premium_price?.toString() || ""); setCurrency(s.currency || "LKR"); setIsActive(s.is_active); setQrUrl(s.qr_image_url || ""); } setLoading(false); } void load(); return () => { mounted = false; }; }, [supabase]);

  async function uploadQr(file: File) { setError(""); setMessage(""); if (!file.type.startsWith("image/")) { setError("Please select an image file."); return; } if (file.size > 5 * 1024 * 1024) { setError("QR image must be 5 MB or smaller."); return; } setUploading(true); const form = new FormData(); form.append("file", file); try { const response = await fetch("/api/admin/payment-qr", { method: "POST", body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "QR upload failed."); setQrUrl(result.url); setMessage("QR image uploaded. Save settings to apply it."); } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : "QR upload failed."); } finally { setUploading(false); } }

  async function save() { setSaving(true); setError(""); setMessage(""); const payload = { payment_method: paymentMethod.trim() || "LankaQR", qr_image_url: qrUrl || null, account_name: accountName.trim() || null, instructions: instructions.trim() || null, is_active: isActive, subject_price: subjectPrice === "" ? null : Number(subjectPrice), premium_price: premiumPrice === "" ? null : Number(premiumPrice), currency: currency.trim().toUpperCase() || "LKR" }; if (payload.subject_price !== null && (!Number.isFinite(payload.subject_price) || payload.subject_price < 0)) { setError("Enter a valid subject price."); setSaving(false); return; } if (payload.premium_price !== null && (!Number.isFinite(payload.premium_price) || payload.premium_price < 0)) { setError("Enter a valid premium price."); setSaving(false); return; } const result = settings?.id ? await supabase.from("payment_settings").update(payload).eq("id", settings.id).select("*").single() : await supabase.from("payment_settings").insert(payload).select("*").single(); if (result.error) setError(result.error.message); else { setSettings(result.data as Settings); setMessage("Payment settings saved successfully."); } setSaving(false); }

  if (loading) return <div className="flex min-h-[400px] items-center justify-center text-sm text-muted-foreground"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading payment settings...</div>;

  return <div className="mx-auto max-w-5xl space-y-8 pb-8">
    <header><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-primary/10 text-primary"><CreditCard className="h-5 w-5" /></div><div><p className="text-sm font-semibold text-primary">Administration</p><h1 className="text-3xl font-extrabold tracking-tight">Payment Settings</h1></div></div><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Configure the payment experience students see when purchasing iSkole subscriptions.</p></header>

    {error && <div className="rounded-2xl border border-destructive/20 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}
    {message && <div className="flex items-center gap-2 rounded-2xl border border-emerald-500/20 bg-emerald-500/5 px-4 py-3 text-sm font-medium text-emerald-700"><CheckCircle2 className="h-4 w-4" />{message}</div>}

    <section className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-5 sm:px-7"><div className="flex items-center justify-between gap-4"><div><h2 className="font-extrabold">Payment availability</h2><p className="mt-1 text-xs text-muted-foreground">Control whether students can submit new paid subscription requests.</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${isActive ? "bg-emerald-500/10 text-emerald-700" : "bg-muted text-muted-foreground"}`}>{isActive ? "Payments active" : "Payments paused"}</span></div></div><div className="p-6 sm:p-7"><label className="flex cursor-pointer items-center justify-between gap-5 rounded-2xl border border-border bg-background p-4 transition hover:border-primary/20"><div><p className="text-sm font-bold">Accept payments</p><p className="mt-1 text-xs leading-5 text-muted-foreground">When disabled, students should not be offered paid plans.</p></div><button type="button" role="switch" aria-checked={isActive} onClick={() => setIsActive((value) => !value)} className={`relative h-7 w-12 shrink-0 rounded-full transition ${isActive ? "bg-primary" : "bg-muted-foreground/25"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow-sm transition ${isActive ? "left-6" : "left-1"}`} /></button></label></div></section>

    <section className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-5 sm:px-7"><h2 className="font-extrabold">Payment method</h2><p className="mt-1 text-xs text-muted-foreground">These details are shown to students during checkout.</p></div><div className="grid gap-5 p-6 sm:grid-cols-2 sm:p-7"><Field label="Payment method" value={paymentMethod} onChange={setPaymentMethod} placeholder="e.g. LankaQR" /><Field label="Account name" value={accountName} onChange={setAccountName} placeholder="e.g. iSkole Online" /></div></section>

    <section className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-5 sm:px-7"><div className="flex items-start gap-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary"><CreditCard className="h-4 w-4" /></div><div><h2 className="font-extrabold">Subscription pricing</h2><p className="mt-1 text-xs text-muted-foreground">Prices used by the public pricing and checkout experience.</p></div></div></div><div className="grid gap-5 p-6 sm:grid-cols-3 sm:p-7"><PriceField label="Subject subscription" value={subjectPrice} onChange={setSubjectPrice} currency={currency} /><PriceField label="Premium subscription" value={premiumPrice} onChange={setPremiumPrice} currency={currency} /><Field label="Currency" value={currency} onChange={(value) => setCurrency(value.toUpperCase().slice(0, 3))} placeholder="LKR" maxLength={3} /></div><div className="mx-6 mb-6 flex items-start gap-3 rounded-2xl bg-muted/40 p-4 sm:mx-7 sm:mb-7"><Info className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" /><p className="text-xs leading-5 text-muted-foreground">Each approved subscription provides 30 days of access. Pricing changes affect new purchases and do not shorten an already active subscription.</p></div></section>

    <section className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-5 sm:px-7"><h2 className="font-extrabold">Payment QR</h2><p className="mt-1 text-xs text-muted-foreground">Upload the QR code students should scan when making a payment.</p></div><div className="grid gap-7 p-6 sm:p-7 lg:grid-cols-[220px_1fr] lg:items-center"><div className="flex aspect-square w-full max-w-[220px] items-center justify-center overflow-hidden rounded-2xl border border-border bg-muted/30 p-3">{qrUrl ? <img src={qrUrl} alt="Payment QR code" className="h-full w-full object-contain" /> : <div className="px-5 text-center text-xs leading-5 text-muted-foreground">No QR image uploaded</div>}</div><div><div className="flex h-10 w-fit items-center rounded-xl border border-border bg-background px-1"><label className="inline-flex h-8 cursor-pointer items-center gap-2 rounded-lg bg-primary px-3 text-xs font-bold text-primary-foreground hover:opacity-90"><Upload className="h-3.5 w-3.5" />{uploading ? "Uploading..." : "Upload QR image"}<input type="file" accept="image/*" className="hidden" disabled={uploading} onChange={(e) => { const file = e.target.files?.[0]; if (file) void uploadQr(file); e.currentTarget.value = ""; }} /></label></div><p className="mt-3 text-xs text-muted-foreground">PNG, JPG, WEBP or GIF · maximum 5 MB.</p><div className="mt-5 rounded-2xl bg-muted/40 p-4"><p className="text-xs font-bold">Tip</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Use a clear, high-resolution QR image with enough contrast for reliable scanning.</p></div></div></div></section>

    <section className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-5 sm:px-7"><h2 className="font-extrabold">Payment instructions</h2><p className="mt-1 text-xs text-muted-foreground">Give students clear instructions for completing their payment.</p></div><div className="p-6 sm:p-7"><textarea value={instructions} onChange={(e) => setInstructions(e.target.value)} rows={7} className="w-full resize-y rounded-2xl border border-input bg-background p-4 text-sm leading-6 outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10" placeholder="Tell students how to make the payment and what reference to include..." /></div></section>

    <div className="sticky bottom-4 z-10 flex justify-end"><button type="button" disabled={saving || uploading} onClick={() => void save()} className="inline-flex h-12 items-center gap-2 rounded-2xl bg-primary px-6 text-sm font-bold text-primary-foreground shadow-lg shadow-primary/20 transition hover:-translate-y-0.5 hover:opacity-95 disabled:cursor-not-allowed disabled:opacity-50"><Save className="h-4 w-4" />{saving ? "Saving changes..." : "Save changes"}</button></div>

    <div className="flex items-center justify-center gap-2 text-[11px] text-muted-foreground"><ShieldCheck className="h-3.5 w-3.5" />Only administrators can change payment settings.</div>
  </div>;
}

function Field({ label, value, onChange, placeholder, maxLength }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; maxLength?: number }) { return <label className="space-y-2 text-sm font-bold"><span>{label}</span><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} maxLength={maxLength} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm font-normal outline-none transition placeholder:text-muted-foreground/50 focus:border-primary focus:ring-4 focus:ring-primary/10" /></label>; }
function PriceField({ label, value, onChange, currency }: { label: string; value: string; onChange: (value: string) => void; currency: string }) { return <label className="space-y-2 text-sm font-bold"><span>{label}</span><div className="relative"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs font-bold text-muted-foreground">{currency || "LKR"}</span><input type="number" min="0" step="0.01" value={value} onChange={(e) => onChange(e.target.value)} className="h-11 w-full rounded-xl border border-input bg-background pl-14 pr-3 text-sm font-normal outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10" /></div></label>; }
