"use client";

import { FormEvent, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import { Eye, EyeOff, LockKeyhole, Mail } from "lucide-react";
import { createClient } from "@/lib/supabase";

export default function LoginPage() {
  const router = useRouter(); const searchParams = useSearchParams(); const redirectTo = searchParams.get("redirect") || "/dashboard";
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [showPassword, setShowPassword] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  async function handleLogin(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); setLoading(true); const supabase = createClient(); const { error: loginError } = await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (loginError) { setError(loginError.message === "Invalid login credentials" ? "The email or password is incorrect." : loginError.message); setLoading(false); return; } router.push(redirectTo); router.refresh(); }
  return <main className="min-h-[calc(100vh-5rem)] bg-background"><div className="mx-auto flex min-h-[calc(100vh-5rem)] max-w-7xl items-center px-4 py-12 sm:px-6 lg:px-8"><div className="grid w-full overflow-hidden rounded-3xl border border-border bg-card shadow-brand-lg lg:grid-cols-2">
    <div className="hidden min-h-[620px] flex-col justify-between bg-primary p-10 text-primary-foreground lg:flex xl:p-14"><div><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/15 text-lg font-bold">iS</div><div><p className="text-lg font-bold leading-none">iSkole</p><p className="mt-1 text-xs text-primary-foreground/70">Learn smarter</p></div></div></div><div><p className="mb-4 text-sm font-semibold uppercase tracking-[0.18em] text-primary-foreground/60">Your learning space</p><h2 className="max-w-lg text-4xl font-bold leading-tight xl:text-5xl">Everything you need to learn, practice and improve.</h2><p className="mt-6 max-w-md text-base leading-7 text-primary-foreground/75">Access your subjects, Question Bank, practice materials and personalised learning tools from one place.</p></div><div className="grid grid-cols-3 gap-3"><Feature label="Question Bank"/><Feature label="Practice"/><Feature label="Learning"/></div></div>
    <div className="flex min-h-[620px] items-center justify-center p-6 sm:p-10 lg:p-14"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-primary text-sm font-bold text-primary-foreground">iS</div><div><p className="font-bold text-foreground">iSkole</p><p className="text-xs text-muted-foreground">Learn smarter</p></div></div></div>
      <div className="mb-8"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.16em] text-primary">iSkole Account</p><h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl">Welcome back</h1><p className="mt-3 text-sm leading-6 text-muted-foreground sm:text-base">Sign in to continue your learning journey.</p></div>
      {error && <div role="alert" className="mb-6 rounded-xl border border-destructive/20 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>}
      <form onSubmit={handleLogin} className="space-y-5"><div><label htmlFor="email" className="mb-2 block text-sm font-semibold text-foreground">Email address</label><div className="relative"><Mail size={18} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground"/><input id="email" name="email" type="email" autoComplete="email" required value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" className="h-12 w-full rounded-xl border border-border bg-background pl-11 pr-4 text-sm text-foreground outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10"/></div></div>
        <div><div className="mb-2 flex items-center justify-between"><label htmlFor="password" className="text-sm font-semibold text-foreground">Password</label><Link href="/forgot-password" className="text-xs font-semibold text-primary transition hover:opacity-80">Forgot password?</Link></div><div className="relative"><LockKeyhole size={18} className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground"/><input id="password" name="password" type={showPassword ? "text" : "password"} autoComplete="current-password" required value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Enter your password" className="h-12 w-full rounded-xl border border-border bg-background pl-11 pr-12 text-sm text-foreground outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10"/><button type="button" aria-label={showPassword ? "Hide password" : "Show password"} onClick={() => setShowPassword((current) => !current)} className="absolute right-3 top-1/2 -translate-y-1/2 rounded-lg p-2 text-muted-foreground transition hover:bg-muted hover:text-foreground">{showPassword ? <EyeOff size={18}/> : <Eye size={18}/>}</button></div></div>
        <button type="submit" disabled={loading} className="flex h-12 w-full items-center justify-center rounded-xl bg-primary px-5 text-sm font-semibold text-primary-foreground shadow-sm transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-60">{loading ? <><span className="mr-2 h-4 w-4 animate-spin rounded-full border-2 border-primary-foreground/30 border-t-primary-foreground"/>Signing in...</> : "Sign in"}</button>
      </form>
      <div className="mt-8 text-center text-sm text-muted-foreground">Don&apos;t have an iSkole account?{" "}<Link href="/register" className="font-semibold text-primary hover:underline">Create one</Link></div><p className="mt-8 text-center text-xs leading-5 text-muted-foreground">By signing in, you agree to use iSkole responsibly for educational purposes.</p>
    </div></div>
  </div></div></main>;
}
function Feature({ label }: { label: string }) { return <div className="rounded-xl border border-white/10 bg-white/10 px-4 py-3"><p className="text-xs font-medium text-primary-foreground/80">{label}</p></div>; }
