"use client";

import { useState } from "react";
import { updatePaymentSettings } from "@/lib/payment-settings-actions";

type Settings = { id: string; payment_method: string; qr_image_url: string | null; account_name: string | null; instructions: string | null; subject_price: number | null; premium_price: number | null; currency: string; is_active: boolean };

export default function PaymentSettingsForm({ initial }: { initial: Settings }) {
  const [form, setForm] = useState({ payment_method: initial.payment_method, qr_image_url: initial.qr_image_url ?? "", account_name: initial.account_name ?? "", instructions: initial.instructions ?? "", subject_price: initial.subject_price?.toString() ?? "", premium_price: initial.premium_price?.toString() ?? "", currency: initial.currency, is_active: initial.is_active });
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const set = (key: keyof typeof form, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  async function save() { setSaving(true); setMessage(""); setError(""); try { await updatePaymentSettings({ id: initial.id, ...form }); setMessage("Payment settings saved."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save payment settings."); } finally { setSaving(false); } }
  return <section className="rounded-2xl border border-border bg-card p-6 shadow-sm sm:p-8"><div className="grid gap-5"><Field label="Payment method"><input value={form.payment_method} onChange={(e) => set("payment_method", e.target.value)} placeholder="LankaQR" /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Subject price (LKR)"><input type="number" min="0" step="0.01" value={form.subject_price} onChange={(e) => set("subject_price", e.target.value)} placeholder="1500" /></Field><Field label="Premium price (LKR)"><input type="number" min="0" step="0.01" value={form.premium_price} onChange={(e) => set("premium_price", e.target.value)} placeholder="3000" /></Field></div><Field label="Currency"><input value={form.currency} onChange={(e) => set("currency", e.target.value.toUpperCase())} placeholder="LKR" /></Field><Field label="QR image URL"><input value={form.qr_image_url} onChange={(e) => set("qr_image_url", e.target.value)} placeholder="https://.../lankaqr.png" /><p className="mt-1 text-xs text-muted-foreground">Use a public image URL for the payment QR. Storage upload can be added later.</p></Field><Field label="Account / merchant name"><input value={form.account_name} onChange={(e) => set("account_name", e.target.value)} placeholder="iSkole Online" /></Field><Field label="Payment instructions"><textarea value={form.instructions} onChange={(e) => set("instructions", e.target.value)} rows={5} placeholder="Scan the QR, complete the payment, then enter your transaction reference and confirm payment." /></Field><label className="flex items-center gap-3 text-sm font-medium text-foreground"><input type="checkbox" checked={form.is_active} onChange={(e) => set("is_active", e.target.checked)} /> Enable manual payment system</label><div className="flex items-center gap-3"><button type="button" onClick={save} disabled={saving} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-60">{saving ? "Saving…" : "Save Payment Settings"}</button>{message && <span className="text-sm font-medium text-emerald-600 dark:text-emerald-400">{message}</span>}{error && <span className="text-sm text-destructive">{error}</span>}</div></div></section>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div><label className="text-sm font-semibold text-foreground">{label}</label><div className="mt-2 [&_input]:w-full [&_input]:rounded-xl [&_input]:border [&_input]:border-border [&_input]:bg-background [&_input]:px-3 [&_input]:py-2.5 [&_input]:text-sm [&_textarea]:w-full [&_textarea]:rounded-xl [&_textarea]:border [&_textarea]:border-border [&_textarea]:bg-background [&_textarea]:px-3 [&_textarea]:py-2.5 [&_textarea]:text-sm">{children}</div></div>; }
