"use client";
import Image from "next/image";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { UserCircle, ChevronDown } from "lucide-react";
import LogoutButton from "@/components/auth/LogoutButton";

const navigation=[{name:"Home",href:"/"},{name:"Notes",href:"/notes"},{name:"Question Bank",href:"/question-bank"},{name:"Mentor",href:"/mentor"},{name:"Dashboard",href:"/dashboard"}];
type UserInfo={email:string;name:string;role:string};
export default function Navbar({user}:{user:UserInfo|null}){
 const pathname=usePathname(); const [mobileMenuOpen,setMobileMenuOpen]=useState(false); const [profileOpen,setProfileOpen]=useState(false);
 const isActive=(href:string)=>href==="/"?pathname==="/":pathname.startsWith(href); const close=()=>setMobileMenuOpen(false); const displayName=user?.name?.trim()||user?.email?.split("@")[0]||"Profile"; const initials=displayName.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();
 return <header className="site-navbar"><div className="navbar-container"><Link href="/" className="navbar-brand" onClick={close} aria-label="iSkole Home"><Image src="/branding/iskole-logo.png" alt="iSkole" width={110} height={42} priority className="navbar-logo-image"/></Link><nav className="navbar-links" aria-label="Main navigation">{navigation.map(item=><Link key={item.href} href={item.href} className={isActive(item.href)?"active":""}>{item.name}</Link>)}</nav><div className="navbar-actions"><button type="button" className="navbar-search" aria-label="Search iSkole" title="Search"><span className="search-icon">⌕</span><span>Search</span></button>{user?<div className="relative"><button type="button" onClick={()=>setProfileOpen(v=>!v)} className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-sm font-semibold" aria-expanded={profileOpen}><span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">{initials||<UserCircle size={18}/>}</span><span className="hidden max-w-32 truncate sm:block">{displayName}</span><ChevronDown size={15}/></button>{profileOpen&&<div className="absolute right-0 z-50 mt-2 w-64 rounded-2xl border border-border bg-card p-2 shadow-xl"><div className="px-3 py-3"><p className="font-semibold truncate">{displayName}</p><p className="mt-1 truncate text-xs text-muted-foreground">{user.email}</p><p className="mt-2 text-xs font-semibold uppercase tracking-wide text-primary">{user.role}</p></div><Link href="/dashboard" onClick={()=>setProfileOpen(false)} className="block rounded-xl px-3 py-2.5 text-sm font-medium hover:bg-muted">Dashboard</Link><div className="mt-1 border-t border-border pt-1"><LogoutButton/></div></div>}</div>:<Link href="/login" className="navbar-login">Login</Link>}</div><div className="navbar-mobile-controls"><button type="button" className="mobile-search-button" aria-label="Search iSkole" title="Search">⌕</button><button type="button" className="mobile-menu-button" onClick={()=>setMobileMenuOpen(v=>!v)} aria-label={mobileMenuOpen?"Close menu":"Open menu"} aria-expanded={mobileMenuOpen}><span/><span/><span/></button></div></div><div className={`mobile-menu ${mobileMenuOpen?"mobile-menu-open":""}`}><nav aria-label="Mobile navigation">{navigation.map(item=><Link key={item.href} href={item.href} className={isActive(item.href)?"active":""} onClick={close}>{item.name}</Link>)}{user?<div className="mt-2 rounded-2xl border border-border bg-card p-2"><div className="px-3 py-2"><p className="font-semibold">{displayName}</p><p className="text-xs text-muted-foreground">{user.email}</p></div><Link href="/dashboard" onClick={close} className="block rounded-xl px-3 py-2.5 text-sm font-medium hover:bg-muted">Profile / Dashboard</Link><LogoutButton/></div>:<Link href="/login" className="mobile-login" onClick={close}>Login</Link>}</nav></div></header>;
}
