"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, ImagePlus, KeyRound, Loader2, Save, ShieldCheck, Upload, UserRound } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Profile = { full_name: string; avatar_url: string; email: string; role: string };
const roleLabels: Record<string, string> = { student: "Student", teacher: "Teacher", admin: "Administrator" };
const roleHome: Record<string, string> = { student: "/student", teacher: "/teacher", admin: "/admin" };

export default function AccountPage() {
  const supabase = useMemo(() => createClient(), []); const fileRef = useRef<HTMLInputElement>(null);
  const [profile, setProfile] = useState<Profile>({ full_name: "", avatar_url: "", email: "", role: "student" }); const [avatarSource, setAvatarSource] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [changingPassword, setChangingPassword] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");

  useEffect(() => { async function load() { const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError("Please sign in to manage your profile."); setLoading(false); return; } const { data, error: profileError } = await supabase.from("profiles").select("full_name,avatar_url,role").eq("id", user.id).maybeSingle(); if (profileError) setError(profileError.message); const avatar = data?.avatar_url ?? ""; setProfile({ full_name: data?.full_name ?? user.user_metadata?.full_name ?? "", avatar_url: avatar, email: user.email ?? "", role: data?.role ?? user.user_metadata?.role ?? "student" }); setAvatarSource(avatar ? `/api/public/avatar/${user.id}?v=${encodeURIComponent(avatar)}` : ""); setLoading(false); } void load(); }, [supabase]);

  async function uploadAvatar(file: File) {
    setError(""); setMessage("");
    if (!file.type.startsWith("image/")) { setError("Please choose an image file."); return; }
    if (file.size > 5 * 1024 * 1024) { setError("Profile pictures must be 5 MB or smaller."); return; }
    setUploading(true);
    try {
      const form = new FormData(); form.append("file", file);
      const response = await fetch("/api/account/avatar", { method: "POST", body: form });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || "Unable to upload the profile picture.");
      const source = `${result.avatarUrl}?v=${Date.now()}`;
      setProfile((current) => ({ ...current, avatar_url: result.path }));
      setAvatarSource(source);
      setMessage("Profile picture updated successfully.");
    } catch (uploadError) {
      setError(uploadError instanceof Error ? uploadError.message : "Unable to upload the profile picture.");
    } finally {
      setUploading(false);
    }
  }

  async function saveProfile(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError("Your session has expired. Please sign in again."); setSaving(false); return; } const name = profile.full_name.trim(); if (!name) { setError("Please enter your full name."); setSaving(false); return; } const { error: updateError } = await supabase.from("profiles").update({ full_name: name }).eq("id", user.id); if (updateError) setError(updateError.message); else { const { error: metadataError } = await supabase.auth.updateUser({ data: { full_name: name } }); if (metadataError) console.warn("Profile metadata update failed:", metadataError.message); setMessage("Profile updated successfully."); } setSaving(false); }
  async function changePassword(event: React.FormEvent) { event.preventDefault(); setChangingPassword(true); setMessage(""); setError(""); if (password.length < 6) { setError("Password must be at least 6 characters."); setChangingPassword(false); return; } if (password !== confirmPassword) { setError("Passwords do not match."); setChangingPassword(false); return; } const { error: passwordError } = await supabase.auth.updateUser({ password }); if (passwordError) setError(passwordError.message); else { setPassword(""); setConfirmPassword(""); setMessage("Password changed successfully."); } setChangingPassword(false); }
  if (loading) return <div className="mx-auto max-w-4xl space-y-5"><div className="h-32 animate-pulse rounded-3xl bg-muted" /><div className="h-80 animate-pulse rounded-3xl bg-muted" /></div>;
  const displayName = profile.full_name || profile.email.split("@")[0] || "User"; const initials = displayName.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "U";
  return <div className="mx-auto max-w-4xl space-y-7 pb-12">
    <header className="flex items-start gap-4"><Link href={roleHome[profile.role] ?? "/"} className="mt-1 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-border bg-card text-muted-foreground transition hover:bg-muted hover:text-foreground" aria-label="Back to dashboard"><ArrowLeft className="h-4 w-4" /></Link><div><p className="text-sm font-semibold text-primary">Account</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight">Profile & Settings</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">Manage your iSkole profile, personal information and account security.</p></div></header>
    {message && <div className="flex items-center gap-2 rounded-2xl border border-emerald-500/20 bg-emerald-500/5 px-4 py-3 text-sm font-semibold text-emerald-700"><Check className="h-4 w-4" />{message}</div>}{error && <div className="rounded-2xl border border-destructive/20 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}
    <section className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm"><div className="relative border-b border-border bg-gradient-to-br from-primary/[0.10] via-primary/[0.035] to-transparent px-6 pb-7 pt-6 sm:px-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><button type="button" onClick={() => fileRef.current?.click()} disabled={uploading} className="group relative flex h-24 w-24 shrink-0 items-center justify-center overflow-hidden rounded-3xl bg-primary/10 text-2xl font-black text-primary ring-4 ring-background shadow-lg disabled:opacity-60" aria-label="Upload profile picture">{avatarSource ? <img src={avatarSource} alt="Profile" className="h-full w-full object-cover" onError={() => setAvatarSource("")} /> : initials}<span className="absolute inset-0 flex items-center justify-center bg-black/45 text-white opacity-0 transition group-hover:opacity-100">{uploading ? <Loader2 className="h-5 w-5 animate-spin" /> : <ImagePlus className="h-5 w-5" />}</span></button><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp,image/gif" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadAvatar(file); event.currentTarget.value = ""; }} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-extrabold truncate">{displayName}</h2><span className="rounded-full bg-primary/10 px-2.5 py-1 text-[11px] font-bold text-primary">{roleLabels[profile.role] ?? "User"}</span></div><p className="mt-1 truncate text-sm text-muted-foreground">{profile.email}</p><button type="button" onClick={() => fileRef.current?.click()} disabled={uploading} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-primary hover:underline"><Upload className="h-3.5 w-3.5" />{uploading ? "Uploading..." : "Change profile picture"}</button><p className="mt-1 text-[11px] text-muted-foreground">PNG, JPG, WebP or GIF · max 5 MB</p></div></div></div>
      <form onSubmit={saveProfile} className="p-6 sm:p-7"><div className="mb-6"><h3 className="font-extrabold">Personal information</h3><p className="mt-1 text-xs text-muted-foreground">Update the information shown on your iSkole account.</p></div><div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><label htmlFor="full_name" className="mb-2 block text-sm font-bold">Full name</label><input id="full_name" value={profile.full_name} onChange={(event) => setProfile((current) => ({ ...current, full_name: event.target.value }))} className="input-field" placeholder="Your name" /></div><div><label htmlFor="email" className="mb-2 block text-sm font-bold">Email address</label><input id="email" value={profile.email} disabled className="input-field cursor-not-allowed opacity-60" /><p className="mt-1.5 text-[11px] text-muted-foreground">Your login email is managed by authentication.</p></div><div><label className="mb-2 block text-sm font-bold">Account type</label><div className="flex h-11 items-center gap-2 rounded-xl border border-border bg-muted/30 px-3 text-sm font-semibold"><UserRound className="h-4 w-4 text-muted-foreground" />{roleLabels[profile.role] ?? "User"}</div></div></div><div className="mt-6 flex justify-end"><button type="submit" disabled={saving} className="inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground shadow-sm disabled:opacity-50">{saving ? <><Loader2 className="h-4 w-4 animate-spin" />Saving...</> : <><Save className="h-4 w-4" />Save changes</>}</button></div></form>
    </section>
    <section className="overflow-hidden rounded-3xl border border-border bg-card shadow-sm"><div className="border-b border-border px-6 py-5 sm:px-7"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><KeyRound className="h-5 w-5" /></div><div><h2 className="font-extrabold">Password & security</h2><p className="mt-1 text-xs text-muted-foreground">Keep your account protected with a strong password.</p></div></div></div><form onSubmit={changePassword} className="p-6 sm:p-7"><div className="grid gap-5 sm:grid-cols-2"><div><label htmlFor="new_password" className="mb-2 block text-sm font-bold">New password</label><input id="new_password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="input-field" placeholder="At least 6 characters" autoComplete="new-password" /></div><div><label htmlFor="confirm_password" className="mb-2 block text-sm font-bold">Confirm password</label><input id="confirm_password" type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} className="input-field" placeholder="Repeat your new password" autoComplete="new-password" /></div></div><div className="mt-5 flex items-start gap-3 rounded-2xl bg-muted/40 p-4"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><p className="text-xs leading-5 text-muted-foreground">Use a unique password that you do not use on other websites.</p></div><div className="mt-5 flex justify-end"><button type="submit" disabled={changingPassword} className="inline-flex h-11 items-center gap-2 rounded-xl border border-border bg-background px-5 text-sm font-bold hover:bg-muted disabled:opacity-50">{changingPassword ? <><Loader2 className="h-4 w-4 animate-spin" />Updating...</> : <><KeyRound className="h-4 w-4" />Change password</>}</button></div></form></section>
    <div className="text-center text-[11px] text-muted-foreground">Your account information is protected by iSkole authentication and access controls.</div>
  </div>;
}
