"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, ImagePlus, KeyRound, Loader2, Save, Upload } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Profile = { full_name: string; avatar_url: string; email: string; role: string };
const roleLabels: Record<string, string> = { student: "Student", teacher: "Teacher", admin: "Administrator" };
const roleHome: Record<string, string> = { student: "/student", teacher: "/teacher", admin: "/admin" };

export default function AccountPage() {
  const supabase = useMemo(() => createClient(), []); const fileRef = useRef<HTMLInputElement>(null);
  const [profile, setProfile] = useState<Profile>({ full_name: "", avatar_url: "", email: "", role: "student" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [changingPassword, setChangingPassword] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState("");
  useEffect(() => { async function load() { const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError("Please sign in to manage your profile."); setLoading(false); return; } const { data, error: profileError } = await supabase.from("profiles").select("full_name,avatar_url,role").eq("id", user.id).maybeSingle(); if (profileError) setError(profileError.message); setProfile({ full_name: data?.full_name ?? user.user_metadata?.full_name ?? "", avatar_url: data?.avatar_url ?? user.user_metadata?.avatar_url ?? "", email: user.email ?? "", role: data?.role ?? user.user_metadata?.role ?? "student" }); setLoading(false); } void load(); }, [supabase]);
  async function uploadAvatar(file: File) { if (!file.type.startsWith("image/")) { setError("Please choose an image file."); return; } if (file.size > 5 * 1024 * 1024) { setError("Profile pictures must be 5 MB or smaller."); return; } setUploading(true); setError(""); setMessage(""); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError("Your session has expired."); setUploading(false); return; } const ext = file.name.split(".").pop()?.toLowerCase() || "jpg"; const path = `${user.id}/avatar.${ext}`; const { error: uploadError } = await supabase.storage.from("profile-images").upload(path, file, { upsert: true, contentType: file.type, cacheControl: "3600" }); if (uploadError) { setError(uploadError.message); setUploading(false); return; } const { data: publicData } = supabase.storage.from("profile-images").getPublicUrl(path); const avatarUrl = `${publicData.publicUrl}?v=${Date.now()}`; const { error: updateError } = await supabase.from("profiles").update({ avatar_url: avatarUrl }).eq("id", user.id); if (updateError) setError(updateError.message); else { setProfile((current) => ({ ...current, avatar_url: avatarUrl })); await supabase.auth.updateUser({ data: { avatar_url: avatarUrl } }); setMessage("Profile picture updated."); } setUploading(false); }
  async function saveProfile(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError("Your session has expired. Please sign in again."); setSaving(false); return; } const { error: updateError } = await supabase.from("profiles").update({ full_name: profile.full_name.trim() }).eq("id", user.id); if (updateError) setError(updateError.message); else { await supabase.auth.updateUser({ data: { full_name: profile.full_name.trim() } }); setMessage("Profile updated successfully."); } setSaving(false); }
  async function changePassword(event: React.FormEvent) { event.preventDefault(); setChangingPassword(true); setMessage(""); setError(""); if (password.length < 6) { setError("Password must be at least 6 characters."); setChangingPassword(false); return; } if (password !== confirmPassword) { setError("Passwords do not match."); setChangingPassword(false); return; } const { error: passwordError } = await supabase.auth.updateUser({ password }); if (passwordError) setError(passwordError.message); else { setPassword(""); setConfirmPassword(""); setMessage("Password changed successfully."); } setChangingPassword(false); }
  if (loading) return <div className="mx-auto max-w-3xl space-y-5"><div className="h-28 animate-pulse rounded-2xl bg-muted" /><div className="h-72 animate-pulse rounded-2xl bg-muted" /></div>;
  const displayName = profile.full_name || profile.email.split("@")[0] || "User"; const initials = displayName.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "U";
  return <div className="mx-auto max-w-3xl space-y-6 pb-12"><div className="flex items-start gap-3"><Link href={roleHome[profile.role] ?? "/"} className="mt-1 flex h-10 w-10 shrink-0 items-center justify-center rounded-xl border border-border bg-card text-muted-foreground transition hover:bg-muted hover:text-foreground" aria-label="Back to dashboard"><ArrowLeft className="h-4 w-4" /></Link><div><p className="text-sm font-semibold text-primary">Account</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight">Profile & Settings</h1><p className="mt-2 text-sm text-muted-foreground">Manage your iSkole profile and account security.</p></div></div>
    {message && <div className="flex items-center gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/5 px-4 py-3 text-sm font-semibold text-emerald-700"><Check className="h-4 w-4" />{message}</div>}{error && <div className="rounded-xl border border-destructive/20 bg-destructive/5 px-4 py-3 text-sm text-destructive">{error}</div>}
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex flex-col gap-5 border-b border-border pb-6 sm:flex-row sm:items-center"><button type="button" onClick={() => fileRef.current?.click()} disabled={uploading} className="group relative flex h-20 w-20 shrink-0 items-center justify-center overflow-hidden rounded-full bg-primary/10 text-xl font-black text-primary disabled:opacity-60" aria-label="Upload profile picture">{profile.avatar_url ? <img src={profile.avatar_url} alt="Profile" className="h-full w-full object-cover" /> : initials}<span className="absolute inset-0 flex items-center justify-center bg-black/45 text-white opacity-0 transition group-hover:opacity-100">{uploading ? <Loader2 className="h-5 w-5 animate-spin" /> : <ImagePlus className="h-5 w-5" />}</span></button><input ref={fileRef} type="file" accept="image/png,image/jpeg,image/webp,image/gif" className="hidden" onChange={(event) => { const file = event.target.files?.[0]; if (file) void uploadAvatar(file); event.currentTarget.value = ""; }} /><div><h2 className="text-lg font-bold">Personal information</h2><p className="mt-1 text-sm text-muted-foreground">Your profile is shared across iSkole.</p><button type="button" onClick={() => fileRef.current?.click()} disabled={uploading} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-primary hover:underline"><Upload className="h-3.5 w-3.5" />{uploading ? "Uploading..." : "Change profile picture"}</button><p className="mt-1 text-[11px] text-muted-foreground">PNG, JPG, WebP or GIF · max 5 MB</p></div></div><form onSubmit={saveProfile} className="mt-6 space-y-5"><div><label htmlFor="full_name" className="mb-2 block text-sm font-semibold">Full name</label><input id="full_name" value={profile.full_name} onChange={(event) => setProfile((current) => ({ ...current, full_name: event.target.value }))} className="input-field" placeholder="Your name" /></div><div><label htmlFor="email" className="mb-2 block text-sm font-semibold">Email address</label><input id="email" value={profile.email} disabled className="input-field cursor-not-allowed opacity-60" /><p className="mt-1.5 text-xs text-muted-foreground">Your login email is managed by your account.</p></div><div><label className="mb-2 block text-sm font-semibold">Account type</label><div className="rounded-xl border border-border bg-muted/30 px-4 py-3 text-sm font-semibold">{roleLabels[profile.role] ?? "User"}</div></div><button type="submit" disabled={saving} className="inline-flex h-11 items-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground disabled:opacity-50">{saving ? <><Loader2 className="h-4 w-4 animate-spin" /> Saving...</> : <><Save className="h-4 w-4" /> Save changes</>}</button></form></section>
    <section className="rounded-2xl border border-border bg-card p-5 sm:p-7"><div className="flex items-center gap-3 border-b border-border pb-5"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary/10 text-primary"><KeyRound className="h-5 w-5" /></div><div><h2 className="text-lg font-bold">Password</h2><p className="text-sm text-muted-foreground">Change your iSkole login password.</p></div></div><form onSubmit={changePassword} className="mt-6 space-y-5"><div><label htmlFor="new_password" className="mb-2 block text-sm font-semibold">New password</label><input id="new_password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="input-field" placeholder="At least 6 characters" autoComplete="new-password" /></div><div><label htmlFor="confirm_password" className="mb-2 block text-sm font-semibold">Confirm password</label><input id="confirm_password" type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} className="input-field" placeholder="Repeat your new password" autoComplete="new-password" /></div><button type="submit" disabled={changingPassword} className="inline-flex h-11 items-center gap-2 rounded-xl border border-border bg-background px-5 text-sm font-bold hover:bg-muted disabled:opacity-50">{changingPassword ? <><Loader2 className="h-4 w-4 animate-spin" /> Updating...</> : <><KeyRound className="h-4 w-4" /> Change password</>}</button></form></section>
  </div>;
}
