"use client";

import { useMemo, useState } from "react";
import { savePracticeResult } from "@/lib/practice-actions";

export type InteractiveQuestion = {
  id: string;
  question_number: number;
  question_type: "mcq" | "structured" | "essay";
  marks: number;
  question_image_url: string | null;
  correct_option: "A" | "B" | "C" | "D" | null;
  answer_text: string | null;
  answer_image_url: string | null;
};

type Mode = "browse" | "practice";
type Option = "A" | "B" | "C" | "D";

export default function QuestionPageInteractive({ questions, pageType, questionPageId }: { questions: InteractiveQuestion[]; pageType: "mcq" | "structured"; questionPageId: string }) {
  const [mode, setMode] = useState<Mode>("browse");
  const totalMarks = useMemo(() => questions.reduce((sum, q) => sum + Number(q.marks || 0), 0), [questions]);
  return <div className="space-y-8">
    <div className="rounded-2xl border border-border bg-card p-2"><div className="grid grid-cols-2 gap-2">
      <ModeButton active={mode === "browse"} onClick={() => setMode("browse")}>Browse Questions</ModeButton>
      <ModeButton active={mode === "practice"} onClick={() => setMode("practice")}>Practice</ModeButton>
    </div></div>
    {mode === "browse" ? <BrowseMode questions={questions} pageType={pageType} totalMarks={totalMarks} /> : pageType === "mcq" ? <McqPractice questions={questions} totalMarks={totalMarks} questionPageId={questionPageId} /> : <StructuredPractice questions={questions} questionPageId={questionPageId} />}
  </div>;
}

function ModeButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) {
  return <button type="button" onClick={onClick} className={`rounded-xl px-4 py-3 text-sm font-semibold transition ${active ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}>{children}</button>;
}

function BrowseMode({ questions, pageType, totalMarks }: { questions: InteractiveQuestion[]; pageType: "mcq" | "structured"; totalMarks: number }) {
  return <div className="space-y-8">{pageType === "mcq" && <div className="rounded-2xl border border-border bg-card px-5 py-4 text-sm text-muted-foreground">Select an option and check each question individually. <span className="ml-2 font-semibold text-foreground">Total: {totalMarks} marks</span></div>}{questions.map(q => <BrowseCard key={q.id} question={q} pageType={pageType} />)}</div>;
}

function BrowseCard({ question, pageType }: { question: InteractiveQuestion; pageType: "mcq" | "structured" }) {
  const [selected, setSelected] = useState<Option | null>(null); const [checked, setChecked] = useState(false); const [showAnswer, setShowAnswer] = useState(false);
  const isMcq = pageType === "mcq" || question.question_type === "mcq"; const correct = selected !== null && selected === question.correct_option;
  return <article className="overflow-hidden rounded-2xl border border-border bg-card"><Header question={question} /><div className="p-5 sm:p-6">{isMcq ? <><QuestionImage question={question} /><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{(["A", "B", "C", "D"] as Option[]).map(option => <button key={option} type="button" onClick={() => { setSelected(option); setChecked(false); setShowAnswer(false); }} className={`rounded-xl border px-4 py-3 font-semibold transition ${checked && option === question.correct_option ? "border-emerald-500 bg-emerald-500/10" : checked && selected === option ? "border-destructive bg-destructive/10" : selected === option ? "border-primary bg-primary text-primary-foreground" : "border-border hover:border-primary/40 hover:bg-primary/5"}`}>{option}</button>)}</div><div className="mt-4 flex flex-wrap gap-3"><button type="button" disabled={!selected} onClick={() => { setChecked(true); setShowAnswer(true); }} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50">Check Answer</button><button type="button" onClick={() => setShowAnswer(v => !v)} className="rounded-xl border border-border px-5 py-2.5 text-sm font-semibold">{showAnswer ? "Hide Answer" : "Show Correct Answer"}</button></div>{checked && selected && <div className={`mt-4 rounded-xl border p-4 ${correct ? "border-emerald-500/30 bg-emerald-500/10" : "border-destructive/30 bg-destructive/10"}`}><p className="font-semibold">{correct ? "Correct!" : "Incorrect."}</p><p className="mt-1 text-sm text-muted-foreground">You scored {correct ? question.marks : 0} / {question.marks} marks.</p></div>}{showAnswer && <AnswerPanel question={question} />}</> : <StructuredViewer question={question} />}</div></article>;
}

function McqPractice({ questions, totalMarks, questionPageId }: { questions: InteractiveQuestion[]; totalMarks: number; questionPageId: string }) {
  const [answers, setAnswers] = useState<Record<string, Option | null>>({}); const [submitted, setSubmitted] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const answered = questions.filter(q => answers[q.id]).length; const correctCount = questions.filter(q => answers[q.id] === q.correct_option).length; const earnedMarks = questions.reduce((sum, q) => sum + (answers[q.id] === q.correct_option ? Number(q.marks || 0) : 0), 0); const percentage = totalMarks ? Math.round((earnedMarks / totalMarks) * 100) : 0;
  async function submit() {
    setSaving(true); setError(null);
    try { await savePracticeResult({ questionPageId, pageType: "mcq", totalQuestions: questions.length, answeredQuestions: answered, correctQuestions: correctCount, earnedMarks, totalMarks, attempts: questions.map(q => ({ questionId: q.id, selectedOption: answers[q.id] ?? null, isCorrect: answers[q.id] ? answers[q.id] === q.correct_option : null, earnedMarks: answers[q.id] === q.correct_option ? Number(q.marks || 0) : 0 })) }); setSubmitted(true); }
    catch (e) { setError(e instanceof Error ? e.message : "Could not save your practice result."); }
    finally { setSaving(false); }
  }
  if (submitted) return <PracticeResults questions={questions} answers={answers} earnedMarks={earnedMarks} totalMarks={totalMarks} percentage={percentage} correctCount={correctCount} answered={answered} />;
  return <div className="space-y-6"><section className="rounded-2xl border border-border bg-card px-5 py-4"><p className="font-semibold">Practice mode</p><p className="mt-1 text-sm text-muted-foreground">Answer all questions first. Answers and marks are revealed after submission.</p></section>{questions.map(q => <article key={q.id} className="overflow-hidden rounded-2xl border border-border bg-card"><Header question={q} /><div className="p-5 sm:p-6"><QuestionImage question={q} /><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">{(["A", "B", "C", "D"] as Option[]).map(option => <button key={option} type="button" onClick={() => setAnswers(current => ({ ...current, [q.id]: option }))} className={`rounded-xl border px-4 py-3 font-semibold transition ${answers[q.id] === option ? "border-primary bg-primary text-primary-foreground" : "border-border hover:border-primary/40 hover:bg-primary/5"}`}>{option}</button>)}</div></div></article>)}{error && <div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}<div className="sticky bottom-4 z-10 flex items-center justify-between gap-4 rounded-2xl border border-border bg-card/95 p-4 shadow-lg backdrop-blur"><p className="text-sm font-semibold">{answered} of {questions.length} answered</p><button type="button" disabled={saving} onClick={submit} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50">{saving ? "Saving..." : "Submit Practice"}</button></div></div>;
}

function PracticeResults({ questions, answers, earnedMarks, totalMarks, percentage, correctCount, answered }: { questions: InteractiveQuestion[]; answers: Record<string, Option | null>; earnedMarks: number; totalMarks: number; percentage: number; correctCount: number; answered: number }) {
  return <div className="space-y-6"><section className="rounded-2xl border border-border bg-card p-8 text-center"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Practice Complete</p><h2 className="mt-3 text-4xl font-bold">{percentage}%</h2><p className="mt-2 text-lg font-semibold">{earnedMarks} / {totalMarks} marks</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Stat label="Questions" value={`${questions.length}`} /><Stat label="Correct" value={`${correctCount}`} /><Stat label="Unanswered" value={`${questions.length - answered}`} /></div><p className="mt-5 text-sm text-muted-foreground">Your result has been saved to your account.</p></section><div className="space-y-6">{questions.map(q => <article key={q.id} className="overflow-hidden rounded-2xl border border-border bg-card"><Header question={q} /><div className="p-5 sm:p-6"><QuestionImage question={q} /><div className="mt-5 rounded-xl border border-border bg-muted/20 p-4"><p className="text-sm text-muted-foreground">Your answer: <b className="text-foreground">{answers[q.id] ?? "Unanswered"}</b></p><p className="mt-1 text-sm text-muted-foreground">Correct answer: <b className="text-foreground">{q.correct_option ?? "Not available"}</b></p><p className={`mt-2 text-sm font-semibold ${answers[q.id] === q.correct_option ? "text-emerald-600" : "text-destructive"}`}>{answers[q.id] ? (answers[q.id] === q.correct_option ? "Correct" : "Incorrect") : "Not answered"}</p></div><AnswerPanel question={q} /></div></article>)}</div></div>;
}

function StructuredPractice({ questions, questionPageId }: { questions: InteractiveQuestion[]; questionPageId: string }) {
  const [revealed, setRevealed] = useState<Record<string, boolean>>({}); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const totalMarks = questions.reduce((s, q) => s + Number(q.marks || 0), 0);
  async function finish() { setSaving(true); setError(null); try { await savePracticeResult({ questionPageId, pageType: "structured", totalQuestions: questions.length, answeredQuestions: Object.values(revealed).filter(Boolean).length, correctQuestions: 0, earnedMarks: 0, totalMarks, attempts: questions.map(q => ({ questionId: q.id, selectedOption: null, isCorrect: null, earnedMarks: 0 })) }); setSaved(true); } catch (e) { setError(e instanceof Error ? e.message : "Could not save practice result."); } finally { setSaving(false); } }
  return <div className="space-y-6"><section className="rounded-2xl border border-border bg-card px-5 py-4"><p className="font-semibold">Practice mode</p><p className="mt-1 text-sm text-muted-foreground">Attempt each structured or essay question first, then reveal the answer to self-check. These questions are not automatically graded.</p></section>{questions.map(q => { const show = Boolean(revealed[q.id]); return <article key={q.id} className="overflow-hidden rounded-2xl border border-border bg-card"><Header question={q} /><div className="p-5 sm:p-6">{show ? <div className="grid gap-6 lg:grid-cols-2 lg:items-start"><QuestionImage question={q} /><div className="lg:sticky lg:top-6"><AnswerPanel question={q} /></div></div> : <QuestionImage question={q} />}<button type="button" onClick={() => setRevealed(current => ({ ...current, [q.id]: !show }))} className="mt-5 rounded-xl border border-border px-4 py-2.5 text-sm font-semibold">{show ? "Hide Answer" : "Reveal Answer"}</button></div></article>; })}{error && <div className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{error}</div>}{!saved && <button type="button" disabled={saving} onClick={finish} className="rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50">{saving ? "Saving..." : "Finish Practice"}</button>}{saved && <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm font-semibold">Practice result saved.</div>}</div>;
}

function StructuredViewer({ question }: { question: InteractiveQuestion }) { const [show, setShow] = useState(false); return <div className="min-h-[70vh]"><div className="mb-5 flex items-center justify-between gap-3"><p className="text-sm font-semibold">{question.question_type === "essay" ? "Essay Question" : "Structured Question"}</p><button type="button" onClick={() => setShow(v => !v)} className="rounded-xl border border-border px-4 py-2 text-sm font-semibold">{show ? "Hide Answer" : "Show Answer"}</button></div>{show ? <div className="grid gap-6 lg:grid-cols-2 lg:items-start"><QuestionImage question={question} /><div className="lg:sticky lg:top-6"><AnswerPanel question={question} /></div></div> : <QuestionImage question={question} />}</div>; }
function QuestionImage({ question }: { question: InteractiveQuestion }) { return question.question_image_url ? <div className="overflow-hidden rounded-xl border border-border bg-muted/20"><img src={question.question_image_url} alt={`Question ${question.question_number}`} className="block h-auto w-full" /></div> : <div className="rounded-xl border border-dashed border-border bg-muted/20 p-8 text-center text-sm text-muted-foreground">No question image has been uploaded yet.</div>; }
function AnswerPanel({ question }: { question: InteractiveQuestion }) { return <div className="rounded-xl border border-primary/20 bg-primary/5 p-5">{question.correct_option && <><p className="text-xs font-semibold uppercase tracking-wide text-primary">Correct Answer</p><p className="mt-2 text-2xl font-bold">{question.correct_option}</p></>}{question.answer_text && <div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wide text-primary">Answer / Explanation</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{question.answer_text}</p></div>}{question.answer_image_url && <div className="mt-4 overflow-hidden rounded-xl border border-border bg-card"><img src={question.answer_image_url} alt={`Answer for question ${question.question_number}`} className="block h-auto w-full" /></div>}{!question.correct_option && !question.answer_text && !question.answer_image_url && <p className="text-sm text-muted-foreground">No answer has been added yet.</p>}</div>; }
function Header({ question }: { question: InteractiveQuestion }) { return <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-5 py-4 sm:px-6"><h2 className="font-bold">Question {question.question_number}</h2><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">{question.marks} {question.marks === 1 ? "mark" : "marks"}</span></div>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-muted/50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>; }
