"use client";

import { useState } from "react";

type Option = "A" | "B" | "C" | "D";
export type InteractiveQuestion = { id:string; question_number:number; question_type:"mcq"|"structured"|"essay"; marks:number; question_image_url:string|null; correct_option:Option|null; answer_text:string|null; answer_image_url:string|null };

export default function QuestionPageInteractive({questions,pageType}:{questions:InteractiveQuestion[];pageType:"mcq"|"structured"}){
 const [answers,setAnswers]=useState<Record<string,Option|null>>({}); const [checked,setChecked]=useState<Record<string,boolean>>({}); const [show,setShow]=useState<Record<string,boolean>>({});
 const total=questions.reduce((s,q)=>s+Number(q.marks||0),0); const earned=questions.reduce((s,q)=>s+(checked[q.id]&&answers[q.id]===q.correct_option?q.marks:0),0); const done=questions.filter(q=>checked[q.id]).length;
 return <div className="space-y-8">{pageType==="mcq"&&<div className="sticky top-3 z-10 rounded-2xl border border-border bg-card/95 px-4 py-3 shadow-sm backdrop-blur sm:px-5 sm:py-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-semibold">MCQ Progress</p><p className="text-xs text-muted-foreground sm:text-sm">{done} of {questions.length} checked</p></div><div className="text-right"><p className="text-base font-bold sm:text-lg">{earned} / {total}</p><p className="text-[11px] text-muted-foreground sm:text-xs">marks</p></div></div></div>}{questions.map(q=><QuestionCard key={q.id} question={q} pageType={pageType} selected={answers[q.id]??null} checked={!!checked[q.id]} showAnswer={!!show[q.id]} onSelect={o=>{setAnswers(a=>({...a,[q.id]:o}));setChecked(c=>({...c,[q.id]:false}));setShow(s=>({...s,[q.id]:false}))}} onCheck={()=>setChecked(c=>({...c,[q.id]:true}))} onShow={()=>setShow(s=>({...s,[q.id]:!s[q.id]}))}/>)}</div>;
}
function QuestionCard({question,pageType,selected,checked,showAnswer,onSelect,onCheck,onShow}:{question:InteractiveQuestion;pageType:"mcq"|"structured";selected:Option|null;checked:boolean;showAnswer:boolean;onSelect:(o:Option)=>void;onCheck:()=>void;onShow:()=>void}){
 const mcq=pageType==="mcq"||question.question_type==="mcq"; const correct=selected!==null&&selected===question.correct_option;
 return <article className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border px-4 py-3 sm:px-6 sm:py-4"><h2 className="text-sm font-bold sm:text-base">Question {question.question_number}</h2><span className="rounded-full bg-primary/10 px-2.5 py-1 text-[11px] font-semibold text-primary sm:px-3 sm:text-xs">{question.marks} {question.marks===1?"mark":"marks"}</span></div><div className="p-4 sm:p-6"><QuestionImage question={question}/>{mcq?<><div className="mt-5 grid grid-cols-2 gap-2 sm:mt-6 sm:grid-cols-4 sm:gap-3">{(["A","B","C","D"] as Option[]).map(o=><button key={o} type="button" onClick={()=>onSelect(o)} className={`min-h-12 rounded-xl border px-3 py-3 text-sm font-semibold transition sm:px-4 ${checked&&o===question.correct_option?"border-emerald-500 bg-emerald-500/10":checked&&selected===o?"border-destructive bg-destructive/10":selected===o?"border-primary bg-primary text-primary-foreground":"border-border hover:border-primary/40 hover:bg-primary/5"}`}>{o}</button>)}</div><div className="mt-3 flex flex-col gap-2 sm:mt-4 sm:flex-row"><button type="button" disabled={!selected} onClick={onCheck} className="min-h-11 rounded-xl bg-primary px-5 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50">Check Answer</button><button type="button" onClick={onShow} className="min-h-11 rounded-xl border border-border px-5 py-2.5 text-sm font-semibold">{showAnswer?"Hide Answer":"Show Correct Answer"}</button></div>{checked&&selected&&<div className={`mt-4 rounded-xl border p-4 ${correct?"border-emerald-500/30 bg-emerald-500/10":"border-destructive/30 bg-destructive/10"}`}><p className="font-semibold">{correct?"Correct!":"Incorrect."}</p><p className="mt-1 text-sm text-muted-foreground">{correct?`You scored ${question.marks}`:"You scored 0"} / {question.marks} marks.</p></div>}{showAnswer&&<AnswerPanel question={question}/>}</>:<><div className="mt-4 flex justify-end"><button type="button" onClick={onShow} className="min-h-11 rounded-xl border border-border px-4 py-2 text-sm font-semibold">{showAnswer?"Hide Answer":"Show Answer"}</button></div>{showAnswer&&<div className="mt-4 grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px] lg:items-start"><div className="rounded-xl border border-border bg-muted/10 p-4 sm:p-5"><p className="text-sm font-semibold">Work through the question before revealing the answer.</p><p className="mt-2 text-sm leading-6 text-muted-foreground">Use the question image above as the paper reference. When you are ready, reveal the teacher-provided answer or explanation.</p></div><div className="lg:sticky lg:top-6"><AnswerPanel question={question}/></div></div>}</>}</div></article>;
}
function QuestionImage({question}:{question:InteractiveQuestion}){return question.question_image_url?<div className="overflow-hidden rounded-xl border border-border bg-muted/20"><img src={question.question_image_url} alt={`Question ${question.question_number}`} className="block h-auto w-full"/></div>:<div className="rounded-xl border border-dashed border-border bg-muted/20 p-8 text-center text-sm text-muted-foreground">No question image has been uploaded yet.</div>}
function AnswerPanel({question}:{question:InteractiveQuestion}){return <div className="mt-4 rounded-xl border border-primary/20 bg-primary/5 p-4 sm:p-5">{question.correct_option&&<><p className="text-xs font-semibold uppercase tracking-wide text-primary">Correct Answer</p><p className="mt-2 text-2xl font-bold">{question.correct_option}</p></>}{question.answer_text&&<div className="mt-4"><p className="text-xs font-semibold uppercase tracking-wide text-primary">Answer / Explanation</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{question.answer_text}</p></div>}{question.answer_image_url&&<div className="mt-4 overflow-hidden rounded-xl border border-border bg-card"><img src={question.answer_image_url} alt={`Answer for question ${question.question_number}`} className="block h-auto w-full"/></div>}{!question.correct_option&&!question.answer_text&&!question.answer_image_url&&<p className="text-sm text-muted-foreground">No answer has been added yet.</p>}</div>}
